---
- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Install pip (Python package manager)
  apt:
    name: python3-pip
    state: present

- name: Install Docker Compose
  pip:
    name: docker-compose
    executable: pip3

- name: Create project directory
  file:
    path: "{{ compose_project_dir }}"
    state: directory
    mode: '0755'

- name: Clone the Git repository
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ compose_project_dir }}"
    version: "{{ git_repo_version }}"
    force: yes

- name: Copy docker-compose.yml to the server
  copy:
    src: docker-compose.yml
    dest: "{{ compose_project_dir }}/docker-compose.yml"
    mode: '0644'

- name: Copy .env file to the server
  copy:
    src: .env
    dest: "{{ compose_project_dir }}/.env"
    mode: '0644'

- name: Pull Docker images
  command: docker-compose pull
  args:
    chdir: "{{ compose_project_dir }}"

- name: Start Docker Compose application
  command: docker-compose up -d
  args:
    chdir: "{{ compose_project_dir }}"

- name: Ensure services are up and running
  command: docker-compose ps
  args:
    chdir: "{{ compose_project_dir }}"




