- name: Check Docker and pip installation on Server
  hosts: "{{ target_group | default('default_group') }}"
  gather_facts: no
  roles:
    - { role: deployment, tags: ["deploy"] }
    - { role: repository_management, tags: ["repo"] }
    